<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><PublishSingleFile>true</PublishSingleFile><EnableCompressionInSingleFile>true</EnableCompressionInSingleFile></PropertyGroup>
  <ItemGroup><Compile Include="../ReleaseProtocol.cs" Link="ReleaseProtocol.cs" /></ItemGroup>
</Project>
