package com.artcatalog.mobile;

import org.json.*;
import java.net.URI;
import java.time.*;
import java.util.*;
import java.util.regex.*;

/** Desktop grouping rules, using publication identities before optional visual evidence. */
final class WorkGrouping {
    static String publication(String raw){try{URI url=URI.create(raw);String host=url.getHost().toLowerCase(Locale.ROOT).replaceFirst("^(www|mobile)\\.","");String path=url.getPath();Matcher match;
        if(host.equals("pixiv.net")){match=Pattern.compile("^/(?:en/)?artworks/(\\d{5,12})(?:/|$)").matcher(path);if(match.find())return "group:pixiv:"+match.group(1);}
        if(host.equals("i.pximg.net")){match=Pattern.compile("/(\\d{5,12})(?:-[a-f0-9]{32})?_p\\d+(?:_[^/.]+)?\\.(?:jpe?g|png|gif|webp)$").matcher(path);if(match.find())return "group:pixiv:"+match.group(1);}
        if(host.equals("x.com")||host.equals("twitter.com")){match=Pattern.compile("^/(?:[^/]+/status|i/web/status)/(\\d{5,25})(?:/|$)").matcher(path);if(match.find())return "original:x-status:"+match.group(1);}
    }catch(Exception ignored){}return "";}
    static Set<String> tokens(Post p){Set<String> keys=new LinkedHashSet<>(p.identityKeys);keys.add("key:"+p.key());for(String key:p.memberKeys)keys.add("key:"+key);if(!p.hash.isBlank())keys.add("hash:"+p.hash.toLowerCase(Locale.ROOT));if(!p.groupKey.isBlank())keys.add("group:"+p.groupKey);if(!p.pixivGroupKey.isBlank())keys.add("group:"+p.pixivGroupKey);String publication=publication(p.originalUrl);if(!publication.isBlank())keys.add(publication);return keys;}
    private static int root(int[] roots,int index){while(roots[index]!=index){roots[index]=roots[roots[index]];index=roots[index];}return index;}
    private static long time(String published){try{return OffsetDateTime.parse(published).toInstant().toEpochMilli();}catch(Exception ignored){}try{return ZonedDateTime.parse(published,java.time.format.DateTimeFormatter.ofPattern("EEE MMM dd HH:mm:ss Z yyyy",Locale.US)).toInstant().toEpochMilli();}catch(Exception ignored){}return -1;}
    private static long id(Post p){try{return Long.parseLong(p.id);}catch(Exception ignored){return -1;}}
    private static long lowTime(Post p){return p.groupMinTime>=0?p.groupMinTime:time(p.published);}
    private static long highTime(Post p){return p.groupMaxTime>=0?p.groupMaxTime:time(p.published);}
    private static long highId(Post p){long value=id(p);for(String key:p.memberKeys)if(key.startsWith(p.source+":"))try{value=Math.max(value,Long.parseLong(key.substring(p.source.length()+1)));}catch(Exception ignored){}return value;}
    private static boolean series(Post a,Post b){if(!a.groupKey.isBlank()||!b.groupKey.isBlank()||!a.pixivGroupKey.isBlank()||!b.pixivGroupKey.isBlank()||!publication(a.originalUrl).isBlank()||!publication(b.originalUrl).isBlank())return false;if(a.artistTag.isBlank()||a.uploaderId.isBlank()||!a.source.equals(b.source)||!a.artistTag.equals(b.artistTag)||!a.uploaderId.equals(b.uploaderId))return false;String ar=CatalogLogic.normalizeRating(a.rating),br=CatalogLogic.normalizeRating(b.rating);if(!(ar.equals("g")&&br.equals("g")||(ar.equals("q")||ar.equals("e"))&&(br.equals("q")||br.equals("e"))))return false;
        long min=Math.min(id(a),id(b)),max=Math.max(id(a),id(b));for(String key:a.memberKeys)if(key.startsWith(a.source+":"))try{long value=Long.parseLong(key.substring(a.source.length()+1));min=Math.min(min,value);max=Math.max(max,value);}catch(Exception ignored){}for(String key:b.memberKeys)if(key.startsWith(b.source+":"))try{long value=Long.parseLong(key.substring(b.source.length()+1));min=Math.min(min,value);max=Math.max(max,value);}catch(Exception ignored){}long at=time(a.published),bt=time(b.published);return min>0&&max-min<=12&&at>=0&&bt>=0&&Math.abs(at-bt)<=600000&&overlap(a.tags,b.tags,12,.78);}
    private static boolean overlap(List<String> a,List<String> b,int minimum,double ratio){Set<String> first=new HashSet<>(a),second=new HashSet<>(b);int common=0;for(String tag:first)if(second.contains(tag))common++;return common>=minimum&&(double)common/(first.size()+second.size()-common)>=ratio;}
    private static boolean fitsGroup(int[] roots,List<Post> items,int current,int previous){int first=root(roots,current),second=root(roots,previous);long min=Long.MAX_VALUE,max=0,minTime=Long.MAX_VALUE,maxTime=0;for(int i=0;i<items.size();i++)if(root(roots,i)==first||root(roots,i)==second){Post p=items.get(i);minTime=Math.min(minTime,lowTime(p));maxTime=Math.max(maxTime,highTime(p));min=Math.min(min,id(p));max=Math.max(max,highId(p));for(String key:p.memberKeys)if(key.startsWith(p.source+":"))try{min=Math.min(min,Long.parseLong(key.substring(p.source.length()+1)));}catch(Exception ignored){}}return min>0&&max-min<=12&&minTime>=0&&maxTime-minTime<=600000;}
    private static JSONArray samples(Post p){if(p.visualSamples.length()>0)return p.visualSamples;JSONArray out=new JSONArray();String owner=!p.uploaderId.isBlank()?p.uploaderId:p.uploaderName;if(p.source.equals("rule34")&&!owner.isBlank()&&p.visualHash.matches("[a-f0-9]{16}")&&p.tags.size()>=3)try{out.put(new JSONObject().put("owner",owner).put("hash",p.visualHash).put("tags",new JSONArray(p.tags)));}catch(JSONException ignored){}return out;}
    private static List<String> strings(JSONArray array){List<String> out=new ArrayList<>();if(array!=null)for(int i=0;i<array.length();i++)out.add(array.optString(i));return out;}
    private static boolean visual(Post a,Post b){JSONArray first=samples(a),second=samples(b);for(int i=0;i<first.length();i++)for(int j=0;j<second.length();j++){JSONObject x=first.optJSONObject(i),y=second.optJSONObject(j);if(x==null||y==null||!x.optString("owner").equals(y.optString("owner")))continue;try{if(Long.bitCount(Long.parseUnsignedLong(x.optString("hash"),16)^Long.parseUnsignedLong(y.optString("hash"),16))<=8&&overlap(strings(x.optJSONArray("tags")),strings(y.optJSONArray("tags")),3,.65))return true;}catch(Exception ignored){}}return false;}
    private static final class Sample {final int index;final long hash;final List<String> tags;Sample(int index,long hash,List<String> tags){this.index=index;this.hash=hash;this.tags=tags;}}
    private static final class HashTree {final long hash;final List<Sample> values=new ArrayList<>();final Map<Integer,HashTree> children=new HashMap<>();HashTree(Sample sample){hash=sample.hash;values.add(sample);}void add(Sample sample){HashTree node=this;while(true){int distance=Long.bitCount(node.hash^sample.hash);if(distance==0){node.values.add(sample);return;}HashTree next=node.children.get(distance);if(next==null){node.children.put(distance,new HashTree(sample));return;}node=next;}}void near(long value,List<Sample> found){ArrayDeque<HashTree> pending=new ArrayDeque<>();pending.add(this);while(!pending.isEmpty()){HashTree node=pending.removeFirst();int distance=Long.bitCount(node.hash^value);if(distance<=8)found.addAll(node.values);for(Map.Entry<Integer,HashTree> child:node.children.entrySet())if(child.getKey()>=distance-8&&child.getKey()<=distance+8)pending.add(child.getValue());}}}
    static List<Post> group(List<Post> a,List<Post> b){List<Post> items=new ArrayList<>(a);items.addAll(b);int[] roots=new int[items.size()];for(int i=0;i<roots.length;i++)roots[i]=i;Map<String,Integer> linked=new HashMap<>();for(int i=0;i<items.size();i++)for(String token:tokens(items.get(i))){Integer previous=linked.putIfAbsent(token,i);if(previous!=null)roots[root(roots,i)]=root(roots,previous);}
        List<Integer> candidates=new ArrayList<>();for(int i=0;i<items.size();i++)candidates.add(i);candidates.sort(Comparator.comparingLong((Integer index)->highId(items.get(index))).reversed());Map<String,List<Integer>> batches=new HashMap<>();for(int i:candidates){Post p=items.get(i);if(p.artistTag.isBlank()||p.uploaderId.isBlank())continue;String bucket=p.source+"|"+p.artistTag+"|"+p.uploaderId;List<Integer> anchors=batches.computeIfAbsent(bucket,key->new ArrayList<>());boolean matched=false;for(int index:anchors)if(series(items.get(index),p)&&fitsGroup(roots,items,i,index)){roots[root(roots,i)]=root(roots,index);matched=true;break;}if(!matched)anchors.add(i);}
        Map<String,HashTree> visualOwners=new HashMap<>();for(int i=0;i<items.size();i++){JSONArray evidence=samples(items.get(i));for(int j=0;j<evidence.length();j++){JSONObject record=evidence.optJSONObject(j);if(record==null)continue;try{String owner=record.optString("owner");if(owner.isBlank())continue;Sample sample=new Sample(i,Long.parseUnsignedLong(record.optString("hash"),16),strings(record.optJSONArray("tags")));HashTree tree=visualOwners.get(owner);if(tree==null)visualOwners.put(owner,new HashTree(sample));else{List<Sample> near=new ArrayList<>();tree.near(sample.hash,near);for(Sample other:near)if(other.index!=i&&overlap(other.tags,sample.tags,3,.65))roots[root(roots,i)]=root(roots,other.index);tree.add(sample);}}catch(Exception ignored){}}}
        LinkedHashMap<Integer,List<Post>> groups=new LinkedHashMap<>();for(int i=0;i<items.size();i++)groups.computeIfAbsent(root(roots,i),key->new ArrayList<>()).add(items.get(i));List<Post> result=new ArrayList<>();for(List<Post> members:groups.values()){Post preferred=members.get(0);for(Post p:members)if(p.source.equals("danbooru")){preferred=p;break;}Post merged=Post.fromJson(preferred.toJson());Set<String> tags=new LinkedHashSet<>(),characters=new LinkedHashSet<>(),artists=new LinkedHashSet<>(),keys=new LinkedHashSet<>(),identities=new LinkedHashSet<>(),urls=new LinkedHashSet<>(),hashes=new HashSet<>(),sampleKeys=new HashSet<>();JSONArray records=new JSONArray(),visuals=new JSONArray();
            long minTime=Long.MAX_VALUE,maxTime=-1;List<Post> ordered=new ArrayList<>(members);ordered.remove(preferred);ordered.add(0,preferred);for(Post p:ordered){if(lowTime(p)>=0){minTime=Math.min(minTime,lowTime(p));maxTime=Math.max(maxTime,highTime(p));}tags.addAll(p.tags);characters.addAll(p.characterTags);artists.addAll(p.artistTags);keys.add(p.key());keys.addAll(p.memberKeys);identities.addAll(tokens(p));if(merged.artistTag.isBlank()&&!p.artistTag.isBlank()){merged.artistTag=p.artistTag;merged.artist=p.artist;}if(merged.originalUrl.isBlank())merged.originalUrl=p.originalUrl;if(p.rating.equals("e"))merged.rating="e";else if(p.rating.equals("q")&&!merged.rating.equals("e"))merged.rating="q";
                JSONArray media=p.imageRecords;if(media.length()==0){media=new JSONArray();for(String url:p.media)try{media.put(new JSONObject().put("url",url).put("hash",p.media.size()==1?p.hash:""));}catch(JSONException ignored){}}for(int i=0;i<media.length()&&records.length()<100;i++){JSONObject record=media.optJSONObject(i);if(record==null)continue;String url=record.optString("url"),hash=record.optString("hash");if(url.isBlank()||urls.contains(url)||!hash.isBlank()&&hashes.contains(hash))continue;urls.add(url);if(!hash.isBlank())hashes.add(hash);records.put(record);}
                JSONArray samples=samples(p);for(int i=0;i<samples.length()&&visuals.length()<100;i++){JSONObject sample=samples.optJSONObject(i);if(sample!=null&&sampleKeys.add(sample.toString()))visuals.put(sample);}
            }merged.groupMinTime=maxTime<0?-1:minTime;merged.groupMaxTime=maxTime;merged.tags=new ArrayList<>(tags);merged.characterTags=new ArrayList<>(characters);merged.artistTags=new ArrayList<>(artists);merged.memberKeys=new ArrayList<>(keys);merged.identityKeys=new ArrayList<>(identities);merged.media=new ArrayList<>(urls);merged.imageRecords=records;merged.visualSamples=visuals;result.add(merged);
        }return result;
    }
}
